id: IBEB93C36
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T02:34:43+00:00'
last_modified: '2022-06-07T13:34:29.004993+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22114
  title: བྱང་གཏེར་འདོན་ཆའི་སྐོར་དཔེ་མཚན་འགའ་ཞིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    31A8:
      image_group_id: I1KG10391
      title: ''
      total_pages: 572
      order: 1
      base_file: 31A8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
