id: IBEB93C36
legacy_id: P000725
ocr_import_info:
  bdrc_scan_id: W22114
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T02:31:11'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T20:42:04.525908+00:00'
last_modified: 2022-09-02 04:42:18.351822
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W22114
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW22114
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བྱང་གཏེར་འདོན་ཆའི་སྐོར་དཔེ་མཚན་འགའ་ཞིག
  author: རིག་འཛིན་རྒོད་ཀྱི་ལྡེམ་འཕྲུ་ཅན།
statistics:
  ocr_word_mean_confidence_index: 0.7509119053720558
  ocr_word_median_confidence_index: 0.8299999833106995
quality: null
bases:
  I1KG10391:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10391
      total_pages: 572
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG10391.txt
    statistics:
      ocr_word_median_confidence_index: 0.8299999833106995
      ocr_word_mean_confidence_index: 0.7509119053720558
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
